const ProductData = [
    {
        "id": 1,
        "name": "LG gram 17인치 노트북",
        "description": "코어 i5 13세대에 10코어(2p+8e)입니다.",
        "count": 30,
        "priceWeek": 47000,
        "priceMonth": 103000,
        "likes": 0,
        "image": "image/desktop-1.png",
        "category": "1"
    },
    {
        "id": 2,
        "name": "애플 에어팟 맥스",
        "description": "하이파이 오디오와 업계최고 수준의 액티브 노이즈 캔슬링, 적응형 EQ, 공간 음향 기능을 갖췄습니다.",
        "count": 30,
        "priceWeek": 19000,
        "priceMonth": 42000,
        "likes": 1,
        "image": "image/sound-1.png",
        "category": "2"
    },
    {
        "id": 3,
        "name": "asus ux331ual 노트북",
        "description": "14인치, i7-8세대 입니다.",
        "count": 30,
        "priceWeek": 23000,
        "priceMonth": 51000,
        "likes": 1,
        "image": "image/desktop-2.png",
        "category": "1"
    },
    {
        "id": 4,
        "name": "터보 사운드 IQ15 스피커 (2500w)",
        "description": "전용가방과 거치대가 포함되어 있습니다. 15인치 우퍼에 2500와트 출력의 앰프가 내장된 파워드 스피커입니다.",
        "count": 30,
        "priceWeek": 30000,
        "priceMonth": 80000,
        "likes": 1,
        "image": "image/sound-2.png",
        "category": "2"
    },
    {
        "id": 5,
        "name": "M2 맥북 에어 고급형",
        "description": "SSD 512g으로 속도저하없이 사용가능합니다.",
        "count": 30,
        "priceWeek": 57000,
        "priceMonth": 113000,
        "likes": 2,
        "image": "image/desktop-3.png",
        "category": "1"
    },
    {
        "id": 6,
        "name": "펜더 스탠다드 일렉기타",
        "description": "9.5“ 곡률의 핑거보드로 되어있습니다.",
        "count": 30,
        "priceWeek": 65000,
        "priceMonth": 140000,
        "likes": 2,
        "image": "image/sound-3.png",
        "category": "2"
    },
    {
        "id": 7,
        "name": "M1 맥북 프로",
        "description": "14.2인치로 램16GB입니다.",
        "count": 30,
        "priceWeek": 52000,
        "priceMonth": 108000,
        "likes": 3,
        "image": "image/desktop-4.png",
        "category": "1"
    },
    {
        "id": 8,
        "name": "Roland 큐브스트리트 스피커",
        "description": "높이 35, 가로 49, 너비 34.1 cm의 7.9kg 입니다.",
        "count": 30,
        "priceWeek": 72000,
        "priceMonth": 185000,
        "likes": 3,
        "image": "image/sound-4.png",
        "category": "2"
    },
    {
        "id": 9,
        "name": "아이패드 프로6세대",
        "description": "11인치입니다.",
        "count": 30,
        "priceWeek": 28000,
        "priceMonth": 67000,
        "likes": 4,
        "image": "image/desktop-5.png",
        "category": "1"
    },
    {
        "id": 10,
        "name": "Shure 핸드마이크",
        "description": "알카라인건전지 또는 SB903 충전배터리를 사용하여 최대 8시간 사용가능합니다.",
        "count": 30,
        "priceWeek": 41000,
        "priceMonth": 105000,
        "likes": 4,
        "image": "image/sound-5.png",
        "category": "2"
    },
    {
        "id": 11,
        "name": "아이패드 5세대",
        "description": "12.9인치입니다.",
        "count": 30,
        "priceWeek": 32000,
        "priceMonth": 75000,
        "likes": 5,
        "image": "image/desktop-6.png",
        "category": "1"
    },
    {
        "id": 12,
        "name": "아카이 MPC live",
        "description": "2개의 USB 3.0단자를 가지고 있습니다.",
        "count": 30,
        "priceWeek": 70000,
        "priceMonth": 180000,
        "likes": 5,
        "image": "image/sound-6.png",
        "category": "2"
    },
    {
        "id": 13,
        "name": "인바이즈 그리드 프로",
        "description": "단축키를 입력할 수 있는 버튼이 있고 노브와 다이얼이 다양해 조절하는 항목에 따라 달리 사용할 수 있습니다.",
        "count": 30,
        "priceWeek": 45000,
        "priceMonth": 100000,
        "likes": 6,
        "image": "image/desktop-7.png",
        "category": "1"
    },
    {
        "id": 14,
        "name": "하만카돈 사운드스틱4 블루투스 스피커",
        "description": "높은 출력, 베이스 우퍼에서 나오는 울림과 저음, 위성스피커를 통해 선명한 사운드를 즐길 수 있습니다.",
        "count": 30,
        "priceWeek": 45000,
        "priceMonth": 135000,
        "likes": 6,
        "image": "image/sound-7.png",
        "category": "2"
    },
    {
        "id": 15,
        "name": "LG 시네빔 PF610P",
        "description": "휴대용 빔프로젝트입니다. FHD, 1000안시루엔으로 언제 어디서나 영화에 몰입할 수 있습니다.",
        "count": 30,
        "priceWeek": 28000,
        "priceMonth": 68000,
        "likes": 7,
        "image": "image/desktop-8.png",
        "category": "1"
    },
    {
        "id": 16,
        "name": "ZOOM H6 핸디레코더",
        "description": "영상제작용 레코더입니다. 최대 녹음 20시간까지 가능합니다.",
        "count": 30,
        "priceWeek": 50000,
        "priceMonth": 140000,
        "likes": 7,
        "image": "image/sound-8.png",
        "category": "2"
    },
    {
        "id": 17,
        "name": "SONY a7m4 카메라",
        "description": "화면비 3:2, 렌즈는 E마운트입니다.",
        "count": 30,
        "priceWeek": 65000,
        "priceMonth": 127000,
        "likes": 0,
        "image": "image/camera-1.png",
        "category": "3"
    },
    {
        "id": 18,
        "name": "산요 작티 빈티지 캠코더 TH1",
        "description": "1280x720, 30fps, 9Mbps입니다.",
        "count": 30,
        "priceWeek": 59000,
        "priceMonth": 59000,
        "likes": 1,
        "image": "image/camera-2.png",
        "category": "3"
    },
    {
        "id": 19,
        "name": "매타퀘스트 2",
        "description": "빠른 전환 LCD 디스플레이, 한쪽당 1832x1920 해상도를 갖고 있으며 안경과 함께 착용 가능합니다.",
        "count": 30,
        "priceWeek": 37000,
        "priceMonth": 93000,
        "likes": 0,
        "image": "image/vr-1.png",
        "category": "4"
    },
    {
        "id": 20,
        "name": "오큘러스 퀘스트2",
        "description": "빠른 전환 LCD 디스플레이, 한쪽당 1832x1920 해상도를 갖고 있습니다.",
        "count": 30,
        "priceWeek": 17000,
        "priceMonth": 44000,
        "likes": 1,
        "image": "image/vr-2.png",
        "category": "4"
    },
    {
        "id": 21,
        "name": "고프로 히어로11",
        "description": "구성은 보조배터리, 플로팅핸들러, 헤드스트랩과 퀵클립도 포함입니다.",
        "count": 30,
        "priceWeek": 34000,
        "priceMonth": 87000,
        "likes": 2,
        "image": "image/camera-3.png",
        "category": "3"
    },
    {
        "id": 22,
        "name": "오큘러스 리프트 S",
        "description": "차세대 렌즈와 더욱 선명한 디스플레이가 밝고 생생한 색상을 전달하며 '스크린도어' 효과를 줄여줍니다.",
        "count": 30,
        "priceWeek": 20000,
        "priceMonth": 48000,
        "likes": 2,
        "image": "image/vr-3.png",
        "category": "4"
    },
    {
        "id": 23,
        "name": "코닥 미니샷 레트로2",
        "description": "신용카드 크기의 사진이 출력가능합니다. 필름은 미포함입니다.",
        "count": 30,
        "priceWeek": 32000,
        "priceMonth": 84000,
        "likes": 3,
        "image": "image/camera-4.png",
        "category": "3"
    },
    {
        "id": 24,
        "name": "퀘스트 프로",
        "description": "직관적으로 재설계된 컨트롤러는 트래킹 링이 필요 없으며 셀프 트레킹 카메라를 이용하여 더 넓은 범위의 동작을 캡쳐할 수 있습니다.",
        "count": 30,
        "priceWeek": 28000,
        "priceMonth": 59000,
        "likes": 3,
        "image": "image/sound-4.png",
        "category": "4"
    },
    {
        "id": 25,
        "name": "SELPHY 포토프린터",
        "description": "스마트폰,노트북, 와이파이연결가능 pc에서 자체와이파이로 연결하여 인화가능합니다.",
        "count": 30,
        "priceWeek": 30000,
        "priceMonth": 79000,
        "likes": 4,
        "image": "image/camera-5.png",
        "category": "3"
    },
    {
        "id": 26,
        "name": "PICO 4 올인원 VR",
        "description": "128GB로, 2160x2160의 해상도를 가지고 있습니다.",
        "count": 30,
        "priceWeek": 20000,
        "priceMonth": 48000,
        "likes": 4,
        "image": "image/vr-5.png",
        "category": "4"
    },
    {
        "id": 27,
        "name": "인스탁스 미니 11",
        "description": "셀피모드도 가능합니다. 필름은 미포함입니다.",
        "count": 30,
        "priceWeek": 14000,
        "priceMonth": 38000,
        "likes": 5,
        "image": "image/camera-6.png",
        "category": "3"
    },
    {
        "id": 28,
        "name": "인스탁스 미니 11",
        "description": "셀피모드도 가능합니다. 필름은 미포함입니다.",
        "count": 30,
        "priceWeek": 14000,
        "priceMonth": 38000,
        "likes": 5,
        "image": "image/camera-6.png",
        "category": "3"
    },
    {
        "id": 29,
        "name": "삼성 기어 VR SM-R325",
        "description": "3D효과, 가상현실체험, 전용앱설치, 파노라믹뷰(360˚) 등의 부가기능을 가지고 있습니다.",
        "count": 30,
        "priceWeek": 10000,
        "priceMonth": 28000,
        "likes": 5,
        "image": "image/vr-6.png",
        "category": "4"
    },
    {
        "id": 30,
        "name": "DJI 팬텀 4 프로",
        "description": "30MB/s쓰기속도 보장하는 128GB 마이크로 SD카드 장착되어 있어 4K 60fps 촬영 가능합니다.",
        "count": 30,
        "priceWeek": 30000,
        "priceMonth": 78000,
        "likes": 6,
        "image": "image/camera-7.png",
        "category": "3"
    },
    {
        "id": 31,
        "name": "DJI mavic mini2",
        "description": "4k 지원, 조종범위 10km, 최대비행시간 31분 입니다.",
        "count": 30,
        "priceWeek": 55000,
        "priceMonth": 150000,
        "likes": 7,
        "image": "image/camera-8.png",
        "category": "3"
    },
    {
        "id": 32,
        "name": "라이카미니룩스 줌",
        "description": "필름 미포함입니다.",
        "count": 30,
        "priceWeek": 64000,
        "priceMonth": 156000,
        "likes": 10,
        "image": "image/camera-11.png",
        "category": "3"
    },
    {
        "id": 33,
        "name": "NG330 유튜브 조명",
        "description": "조명 하나 당 형광등 6구씩 들어가 있는 높은 광량의 제품입니다.",
        "count": 30,
        "priceWeek": 25000,
        "priceMonth": 67000,
        "likes": 8,
        "image": "image/camera-9.png",
        "category": "3"
    },
    {
        "id": 34,
        "name": "고독스 sl60w",
        "description": "소프트박스연결, LED라이트내장, 조명고정, 광량조절",
        "count": 30,
        "priceWeek": 32000,
        "priceMonth": 77000,
        "likes": 9,
        "image": "image/camera-10.png",
        "category": "3"
    }
]

export default ProductData;